import Head from "next/head";
import Hero from "../components/Hero";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <Box pt={100}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    </Box>
  );
}
